version: '3'
services:
    front:
        container_name: front
        build: ./front
        depends_on:
            - back
        ports:
            - "3000:3000"
        restart: on-failure
    back:
        container_name: back
        build: ./back
        depends_on:
            - mongo
        networks:
            - back_net
        environment:
            PORT: 8080
            MONGO_USER: admin
            MONGO_PASSWORD: adpass
            MONGO_HOST: mongo
        ports:
            - "8080:8080"
        restart: on-failure
    mongo:
        container_name: mongo
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: adpass
            MONGO_INITDB_DATABASE: dbapp
        ports:
            - "27017:27017"
        volumes:
            - db-data:/data/db
        networks:
            - back_net
        restart: on-failure
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: adpass
        networks:
                - back_net
    mongo-seed:
        image: mongo
        links:
            - mongo
        volumes:
            - ./db-seed:/db-seed
        command:
            /db-seed/import.sh
        depends_on:
            - mongo
        networks:
            - back_net
networks:
    back_net:
volumes:
    db-data:
    db-seed:
